[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache'

evm_version="shanghai"

remappings = [
	"maat-v1-core/=lib/maat-v1-core/src/",
]

[rpc_endpoints]
arbitrum = "${ARBITRUM_RPC}"
base = "${BASE_RPC}"
metis = "${METIS_RPC}"
sei = "${SEI_RPC}"
